### PR TITLE
Attempt 2: If the user does not specify a wcs object, makes a default wcs.

### LINKED ISSUE #156: Relax Requirement that NDCube must include a WCS object
### Description

Currently is it required that each ```NDCube``` instance has a ```WCS``` instance attached to it.  However, coordinated can be expressed in the form of ```extra_coords```.  Therefore, it may be that users do not need or want to use the ```WCS``` features of ```NDCube```.

Most cases where ```WCS``` is assumed, e.g. slicing, can be altered with an ```if``` statement checking whether ```NDCube.wcs is None``` and only performed that task if this statement is ```False```.  In ```NDCube.plot``` ```WCS``` is assumed by default.  In this case, if ```NDCube.wcs is None```, axes can be given in pixel units.  If users want to describe their axes using ```extra_coords```, capabilities already exits to do this explicitly.

### PR DESCRIPTION
**Pull request by DanRyanIrish**
### Description

This is the same as PR #170 with some updated merges.  It relaxes requirement that user must input wcs object. If user does not provide one, a default object is created from the dataset.

Fixes #156

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
@gnshafreak would you care to give this PR a quick review since it's mainly your work?

**Comment by DanRyanIrish** [comment]
@kakirastern could you give this PR a quick review?

**Comment by kakirastern** [comment]
Sure. Looks good to me, except missing a space in the printout content on this line [https://github.com/sunpy/ndcube/pull/175/files#diff-f11535c008826494ebd27b9f4b2dbaa8R190](https://github.com/sunpy/ndcube/pull/175/files#diff-f11535c008826494ebd27b9f4b2dbaa8R190) for the error thrown. So `"Cannot set missing_axes without supplyinga WCS."` should be `"Cannot set missing_axes without supplying a WCS."`

**Comment by kakirastern** [comment]
Checked all the dimensions and ordering too. Looks like it's good to merge.

**Comment by DanRyanIrish** [comment]
ping @Cadair.

**Comment by Cadair** [comment]
@DanRyanIrish You mind if I rebase this onto the 2.0 (ape14) branch?

**Comment by DanRyanIrish** [comment]
Go for it!

**Comment by Cadair** [comment]
@DanRyanIrish I have rebased it onto the new branch, I am 100% sure I have broken it though, would you be able to pick it back up and clean it up now missing_axes etc is no longer a thing?

**Comment by DanRyanIrish** [comment]
OK, I'll try to make time.

**Pull request closed without merging**
