### PR TITLE
Add links to ndcube publications to README and docs.

### PR DESCRIPTION
**Pull request by DanRyanIrish**

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by Cadair** [comment]
My only thought about this is if we should have a project-wide citation file? i.e. extend [this](https://github.com/sunpy/sunpy/blob/main/sunpy/CITATION.rst) one which get's pulled into the website etc?

**Comment by nabobalis** [comment]
What would be the best way to host it? In our .github repo and add to that? 

Add a file and convert it to html on the sunpy.org website?

**Comment by Cadair** [comment]
Well if we add all the various project ones to the one in core it will "just work"?

**Comment by nabobalis** [comment]
Sounds good

**Pull request merged**
