### PR TITLE
added: ndcube github repo link in doc

### LINKED ISSUE #391: Provide ndcube github repository link in installation guide.
The GitHub link mentioned in installation guide isn't heading towards ndcube github repository.

`https://docs.sunpy.org/projects/ndcube/en/stable/installation.html#installing-the-development-version
`

so to fix this, the link should be given as  `https://github.com/sunpy/ndcube` inside file `ndcube/docs/installation.rst`

### PR DESCRIPTION
**Pull request by Kate028**
Fixes #391

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Hi @Kate028.  Thanks so much for spotting this bug and submitting this PR.  It looks like the codestyle test is failing.  Could you fix this by running
`tox -e codestyle`
from a terminal in the top level directory of your local ndcube repo and committing and pushing the code changes it makes?  Once the tests are passing we can merge!

**Comment by Kate028** [comment]
Hey @DanRyanIrish  after running this command `tox -e codestyle`  , some log file got created named .tox-0.log within .tox as
`ndcube/.tox/.tox/log/.tox-0.log` . Also, it having records of installations. Should i delete this file before committing? or this is the change you were talking about?

**Comment by Kate028** [comment]
Also, i was thinking if changelog entry is needed for this small issue or not.

**Comment by nabobalis** [comment]
> Hey @DanRyanIrish after running this command `tox -e codestyle` , some log file got created named .tox-0.log within .tox as
> `ndcube/.tox/.tox/log/.tox-0.log` . Also, it having records of installations. Should i delete this file before committing? or this is the change you were talking about?

That folder is ignored by git.

**Review by DanRyanIrish — APPROVED** [review]

**Comment by DanRyanIrish** [comment]
Merged!  Thanks @Kate028 for fixing this bug.

**Comment by Kate028** [comment]
My Pleasure @DanRyanIrish  : ) Thanks for all the guidance.

**Pull request merged**
