### PR TITLE
Lets try to build some docs?

### LINKED ISSUE #62: Fix the RTD build

### PR DESCRIPTION
**Pull request by nabobalis**
It might fix #62

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Thanks @nabobalis!  Hopefully this works.

**Comment by DanRyanIrish** [comment]
Does this have to be merged to see if it fixes RTD?

**Comment by Cadair** [comment]
I don't think this works

**Comment by Cadair** [comment]
Astropy found that it does not respect the pin, we can merge it and see though.

**Comment by nabobalis** [comment]
Any pin? We can hard fix it instead

**Comment by DanRyanIrish** [comment]
Merging this doesn't appear to have fixed the docs judging from just refreshing the URL.  Perhaps someone else can confirm?

Does SunPy also have this problem?  Or do we not see it because there hasn't been a release since sphinx 1.7?

Is the only solution then to wait until sphinx fixes this bug?

**Comment by nabobalis** [comment]
```
Running Sphinx v1.7.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndcube/conda/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndcube/conda/latest/lib/python2.7/site-packages/sphinx/application.py", line 162, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndcube/conda/latest/lib/python2.7/site-packages/sphinx/config.py", line 163, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (ndcube.py, line 27)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (ndcube.py, line 27)
```

That is a very different error now. Ill try locally later on today.

**Pull request merged**
