### PR TITLE
fixing the error of slicing across one cube in cubesequence 

### PR DESCRIPTION
**Pull request by abit2**
like seq[0:1] for cube with first dimension size 2.
@DanRyanIrish

### CODE REVIEW

**Comment by abit2** [comment]
Can you please give me an example in which the code break because of https://github.com/sunpy/ndcube/blob/master/ndcube/cube_utils.py#L185

**Comment by DanRyanIrish** [comment]
Hi @abit2.  Can you give an example of the error that this PR fixes?  I'll try to come up with an example of the other error I told you about.

**Comment by abit2** [comment]
```
from collections import namedtuple
import pytest

import numpy as np
import astropy.units as u
import sunpy.map

from ndcube import NDCube, NDCubeSequence
from ndcube import cube_utils as cu
from ndcube.wcs_util import WCS


SequenceDimensionPair = namedtuple('SequenceDimensionPair', 'shape axis_types')

# sample data for tests
# TODO: use a fixture reading from a test file. file TBD.
data = np.array([[[1, 2, 3, 4], [2, 4, 5, 3], [0, -1, 2, 3]],
                 [[2, 4, 5, 1], [10, 5, 2, 2], [10, 3, 3, 0]]])

data2 = np.array([[[11, 22, 33, 44], [22, 44, 55, 33], [0, -1, 22, 33]],
                  [[22, 44, 55, 11], [10, 55, 22, 22], [10, 33, 33, 0]]])

ht = {'CTYPE3': 'HPLT-TAN', 'CUNIT3': 'deg', 'CDELT3': 0.5, 'CRPIX3': 0, 'CRVAL3': 0, 'NAXIS3': 2,
      'CTYPE2': 'WAVE    ', 'CUNIT2': 'Angstrom', 'CDELT2': 0.2, 'CRPIX2': 0, 'CRVAL2': 0,
      'NAXIS2': 3,
      'CTYPE1': 'TIME    ', 'CUNIT1': 'min', 'CDELT1': 0.4, 'CRPIX1': 0, 'CRVAL1': 0, 'NAXIS1': 4}

hm = {
    'CTYPE1': 'WAVE    ', 'CUNIT1': 'Angstrom', 'CDELT1': 0.2, 'CRPIX1': 0, 'CRVAL1': 10,
    'NAXIS1': 4,
    'CTYPE2': 'HPLT-TAN', 'CUNIT2': 'deg', 'CDELT2': 0.5, 'CRPIX2': 2, 'CRVAL2': 0.5, 'NAXIS2': 3,
    'CTYPE3': 'HPLN-TAN', 'CUNIT3': 'deg', 'CDELT3': 0.4, 'CRPIX3': 2, 'CRVAL3': 1, 'NAXIS3': 2,
}

wt = WCS(header=ht, naxis=3)
wm = WCS(header=hm, naxis=3)

cube1 = NDCube(data, wt, missing_axis=[False, False, False, True])
cube2 = NDCube(data, wm)
cube3 = NDCube(data2, wt, missing_axis=[False, False, False, True])
cube4 = NDCube(data2, wm)

seq = NDCubeSequence([cube1, cube2, cube3, cube4], common_axis=0)
seq.index_as_cube[0:1]
```
fails with this error
```
In [2]: seq.index_as_cube[0:1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-3d2e46e5bd84> in <module>()
----> 1 seq.index_as_cube[0:1]

~/workspace/GSOC/ndcube/ndcube/ndcube.py in __getitem__(self, item)
    695 
    696     def __getitem__(self, item):
--> 697         return cube_utils.index_sequence_as_cube(self.seq, item)
    698 
    699 

~/workspace/GSOC/ndcube/ndcube/cube_utils.py in index_sequence_as_cube(cubesequence, item)
    185         return get_cube_from_sequence(cubesequence, item_tuple[1::])
    186     else:
--> 187         return get_cube_from_sequence(cubesequence, item_tuple, type_slice='sequence_as_cube')
    188 
    189 

~/workspace/GSOC/ndcube/ndcube/cube_utils.py in get_cube_from_sequence(cubesequence, item, type_slice)
     74             data = result.data[item[0]]
     75             # applying the slice in the start of cube.
---> 76             data[0] = data[0][item[1][0]]
     77             if len(item[1]) is 2:
     78                 # applying the slice in the end of cube.

TypeError: 'slice' object is not subscriptable

In [3]: 
```

**Comment by DanRyanIrish** [comment]
Ah I see what you're talking about! :)  Thanks!

**Pull request merged**
