### PR TITLE
1.4 sequence plotting sunpy21

### PR DESCRIPTION
**Pull request by DanRyanIrish**
Backports #294 to the 1.4 branch and includes handling of ```missing_axes```.

### CODE REVIEW

**Comment by Cadair** [comment]
you made the CI angry :stuck_out_tongue:

**Comment by Cadair** [comment]
Your getting closer :p

**Comment by DanRyanIrish** [comment]
Thanks!  I think this is ready for a review @Cadair.  There are two outstanding issues.  
1. The tests fail for sunpy master because `ImageAnimatorWCS` and `LineAnimator` are no longer present.  Fixing this would require refactoring the `NDCube` plotting code as well as the `NDCubeSequence` code which this PR already alters.  This refactor would be divergent from ndcube master which uses your new plotting infrastructure.
2. There appears to be a failure on the windows test which doesn't appear in the others.  I'm not sure why this happens.  From the error log it looks like its some incompatibility of wcsaxes with windows...

**Comment by DanRyanIrish** [comment]
This PR is made unnecessary by PR #306

**Pull request closed without merging**
