### PR TITLE
Helpers to v3.0 and another RTD fix.

### PR DESCRIPTION
**Pull request by nabobalis**
If you are python 3 only, might as well use the latest version of helpers. 

Also the this time the RTD build issue is my fault from my last PR.

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
So this just restores the  .rtd-environment.yml to the original state.  It doesn't try to solve the RTD issue.

Also, what exactly does helpers actually do?  I guess you're right, we might as well use the new version.  Do we know what new capability this new version has?

**Comment by DanRyanIrish** [comment]
@nabobalis can you try to address the PEP8 complaints where it's easy to so?

**Comment by nabobalis** [comment]
Well the docs build locally for me under 1.7. There are some API errors from the build.

```
<autosummary>:: WARNING: toctree contains reference to document 'api/ndcube.DimensionPair' that doesn't have a title: no link will be generated
<autosummary>:: WARNING: toctree contains reference to document 'api/ndcube.NDCube' that doesn't have a title: no link will be generated
b'<partial node>':: WARNING: toctree contains reference to document 'api/ndcube.DimensionPair' that doesn't have a title: no link will be generated
b'<partial node>':: WARNING: toctree contains reference to document 'api/ndcube.NDCube' that doesn't have a title: no link will be generated
/home/nabil/Git/ndcube/docs/index.rst:: WARNING: toctree contains reference to document 'api/ndcube.DimensionPair' that doesn't have a title: no link will be generated
/home/nabil/Git/ndcube/docs/index.rst:: WARNING: toctree contains reference to document 'api/ndcube.NDCube' that doesn't have a title: no link will be generated
build succeeded, 52 warnings.
```

**Comment by nabobalis** [comment]
Also those PEP8 errors are fore files we inherit from `astropy_heplers` and should be ignored (https://github.com/sunpy/ndcube/blob/master/.pep8speaks.yml) by the bot but for some reason it doesn't happen.

**Comment by DanRyanIrish** [comment]
Hmmm.  So why does it build online?  Is it because of those errors?

We don't use the ```DimensionPair``` object anymore so we should remove that.  That should solve that API error.  I'll add that to PR #60.  Maybe the NDCube API error is related also.

OK, forget those PEP8 errors then :)

**Comment by nabobalis** [comment]
Oh those build errors are me not cleaning my local repo between builds!

**Comment by nabobalis** [comment]
Do you mind if I make a minor change to pep8 bot and to your travis setup?!

**Comment by nabobalis** [comment]
Also how you finding the use of `pycodestyle`? It is something I would like to add to main sunpy down the road.

**Comment by DanRyanIrish** [comment]
@nabobalis, go ahead so long as you can clean up any mess in the history you accidentally make :)

Again, I defer to @Cadair on the ```pycodestyle``` question.  I haven't noticed any different but that's probably me being unobservant.

**Comment by nabobalis** [comment]
YOU

**Comment by nabobalis** [comment]
YOU

**Comment by nabobalis** [comment]
YOU

**Comment by nabobalis** [comment]
I

**Comment by nabobalis** [comment]
HAVE

**Comment by nabobalis** [comment]
NO

**Comment by nabobalis** [comment]
WORDS

**Comment by nabobalis** [comment]
RIGHT

**Comment by nabobalis** [comment]
NOW

**Comment by DanRyanIrish** [comment]
What's up @nabobalis ???

**Comment by nabobalis** [comment]
I WAS JUST ABOUT TO UPDATE THIS

**Comment by DanRyanIrish** [comment]
Hahaha!  Just open another PR from the same branch?

**Comment by Cadair** [comment]
It worked though!

**Comment by DanRyanIrish** [comment]
Yay!!!  What fixed it?

**Comment by Cadair** [comment]
The helpers update I think.

**Comment by DanRyanIrish** [comment]
Brilliant!!!

So now we just need to merge get PR #60 merged before we are at 1.0! :D

**Pull request merged**
