### PR TITLE
Make quantity definitions in docs less verbose.

### LINKED ISSUE #129: The examples in guide use very verbose quantity construction examples
i.e this: http://docs.sunpy.org/projects/ndcube/en/latest/ndcube.html#coordinate-transformations

it should all be `*u.deg` etc rather than using the `Quantity` constructor.

### PR DESCRIPTION
**Pull request by DanRyanIrish**
### Description

Fixes #129

### CODE REVIEW

**Comment by nabobalis** [comment]
Circle is working again!  Let us see if Giles appears.

**Comment by DanRyanIrish** [comment]
Yay!

**Comment by nabobalis** [comment]
So @Cadair needs to turn on the sunpy bot and giles.

**Comment by Cadair** [comment]
Done.

**Comment by Cadair** [comment]
Looks like there are a few others in that file, specifically the [slicing](https://github.com/sunpy/ndcube/blob/196eeecfca338784cd8cffa409b1e4c68f835654/docs/ndcube.rst#slicing) section?

**Comment by nabobalis** [comment]
TODO: Will need to change the changelog entry part.

**Comment by DanRyanIrish** [comment]
> Looks like there are a few others in that file, specifically the [slicing](https://github.com/sunpy/ndcube/blob/196eeecfca338784cd8cffa409b1e4c68f835654/docs/ndcube.rst#slicing) section?

Fixed, @Cadair.

**Comment by Cadair** [comment]
The error is higher up in the log output than that @DanRyanIrish : https://dev.azure.com/sunpy/ndcube/_build/results?buildId=1511&view=logs&jobId=00f3787d-38f3-5cb2-89da-5d1e94a8bfbe&taskId=29a36215-68ca-52a8-963a-902211c70eb1&lineStart=70&lineEnd=70&colStart=1&colEnd=35

(`u` is not defined)

We should move to towncrier based changelogs

**Comment by nabobalis** [comment]
I decided that moving the changelog system was not my call to make. You two need to make the choice.

**Comment by nabobalis** [comment]
I should also add a comment to the dev docs over that tox issue. It is quite common for people to see that message and go what is this nonsense

**Comment by Cadair** [comment]
We also need to set up the test report uploading to azure...

**Comment by nabobalis** [comment]
I'll add it to my todo list.

**Comment by DanRyanIrish** [comment]
I don't understand the differences between towncrier and whatever the setup in now, so I don't feel I can make an informed choice...

**Comment by nabobalis** [comment]
@Cadair can explain it better than I can.

**Comment by DanRyanIrish** [comment]
Well apart from a changelog entry which I don't think we need for a change like this, all the test are passing.  Can I get an approval for this PR, @Cadair?

**Comment by Cadair** [comment]
I assume we need to pull the bot config in?

**Comment by DanRyanIrish** [comment]
Ummm... ?

**Comment by Cadair** [comment]
The label should have made the bot test pass.

**Comment by nabobalis** [comment]
sunpy bot and towncrier config is already in place.

**Comment by nabobalis** [comment]
The milestone was the issue?

**Comment by Cadair** [comment]
Oh yeah. Cool Cool.

**Pull request merged**
