### PR TITLE
Add installation instructions to docs.

### PR DESCRIPTION
**Pull request by DanRyanIrish**

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
@Cadair do you know why sphinx is failing here?

**Comment by DanRyanIrish** [comment]
@Cadair Can this doc change be retroactively put into 1.0?  Or is that ill-advised?

**Comment by nabobalis** [comment]
You could rebuild the docs and point it to the new version. If they don't already point to latest on RTD.

**Comment by Cadair** [comment]
you indented poorly: https://travis-ci.org/sunpy/ndcube/jobs/346280883#L1095

We can cherry-pick this into stable, which means it will be in the default docs rather than it technically making it into the "1.0" release.

**Comment by nabobalis** [comment]
Also remove the doc_fix branch.

**Comment by DanRyanIrish** [comment]
@Cadair How many spaces should the indentation be?  I've tried a number of options and they've all errored.

**Comment by Cadair** [comment]
I think you need a line break after the `.. code-block` line.

**Pull request merged**
