### PR TITLE
Rename ExtraCoords method 'add_coordinates' to 'add'

### PR DESCRIPTION
**Pull request by rosteen**
### Description

Addresses the `add` half of #348. It sounds like there needs to be a `remove` method added as well, and while I assume that needs to do exactly what it sounds like I figured I'd hold off for now in case there are more details or it can wait for 2.1.

### CODE REVIEW

**Review by DanRyanIrish — CHANGES_REQUESTED** [review]
Hi @rosteen.  This looks great.  Could you add a changelog file to the changelog directory?  In case you are used to a different way of doing the changelog, ndcube follows the same way as sunpy, outlined here: https://github.com/sunpy/sunpy/blob/master/changelog/README.rst

Also you need to make the codestyle fix I suggested to get the tests passing.  Note the line below my suggestion also needs its indentation fixed.

**Comment by DanRyanIrish** [comment]
Hi @rosteen.  Looks like you failed to include the indentation changes in your latest commit.

**Comment by rosteen** [comment]
Whoops, the good old "forget to git add a file before committing", thanks for the heads up.

**Comment by DanRyanIrish** [comment]
> Whoops, the good old "forget to git add a file before committing", thanks for the heads up.

That's exactly what I suspected happened :)

**Review by DanRyanIrish — APPROVED** [review]

**Comment by DanRyanIrish** [comment]
Merged!  Thanks @rosteen for this PR.  Another small step towards 2.0!  If you would like to attack any of the other issues I mentioned to you and have any questions, let me know.

**Pull request merged**
