### PR TITLE
JUST TO SEE IF CIRCLE WILL WORK

### PR DESCRIPTION
**Pull request by nabobalis**
JUST TO SEE IF CIRCLE WILL WORK

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Hi @nabobalis.  Only seeing this now.  Did it work?

**Comment by nabobalis** [comment]
No, I thought it would trigger the CI but nothing happened. I don't have anything in my fork to open a fresh PR with.

**Comment by DanRyanIrish** [comment]
OK.  So how do I "kick" an open PR?

**Comment by nabobalis** [comment]
I think either adding another commit or if you amend a commit and force push.

**Comment by DanRyanIrish** [comment]
OK, thanks.

**Pull request closed without merging**
