### PR TITLE
Revert "Skip a test until astropy 6.1.3 is released"

### PR DESCRIPTION
**Pull request by Cadair**
Reverts sunpy/ndcube#752 as astropy 6.1.3 is out.

### CODE REVIEW

**Comment by Cadair** [comment]
oh goodie the fixes to wcs_info_str landed and now that's broken.

**Comment by nabobalis** [comment]
You can just fix it?

**Comment by Cadair** [comment]
Sure, just not with 3 clicks on GH from my phone.

**Comment by nabobalis** [comment]
Yeah, I feel you.

Time to start setting up a dev environment on my phone

**Pull request merged**
