### PR TITLE
overhaul of conda setup on azure

### PR DESCRIPTION
**Pull request by nabobalis**
Should fix the conda issue on the CI.

### CODE REVIEW

**Comment by nabobalis** [comment]
Failures due to ndcube failing on sunpy 1.0 but the conda env now does run correctly.

**Comment by nabobalis** [comment]
Old sunpy test is passing.

**Comment by DanRyanIrish** [comment]
Looks good.  Any reason I shouldn't merge, @nabobalis?

**Comment by nabobalis** [comment]
Should be good to merge.

**Comment by DanRyanIrish** [comment]
Thanks @nabobalis!!

**Pull request merged**
