### PR TITLE
Bugfix in indexing CubeSequence as cube.

### PR DESCRIPTION
**Pull request by DanRyanIrish**
This PR fixes a bug in indexing cube sequences as cubes.

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Hi @abit2.  Do you remember what the use case for this elif statement was?  I found that it was actually causing NDCubeSequence.index_as_cube to crash.  Is it needed at all or have I just forgotten a use case?

**Comment by abit2** [comment]
yes it was based on the input of the user like 
```
index_as_cube[0]
OR
index_as_cube[0:3]
OR
index_as_cube[0,0:3,:]
OR
index_as_cube[0:4, :]
```
@DanRyanIrish

**Comment by DanRyanIrish** [comment]
@abit2 So you approve of this ```try...except...``` change?

**Comment by abit2** [comment]
yes

**Comment by DanRyanIrish** [comment]
Great!  Thanks!

**Pull request merged**
