### PR TITLE
Add pages on How to Contribute and Getting Help Pages to the Guide

### PR DESCRIPTION
**Pull request by DanRyanIrish**
This PR adds a Getting Help and How to Contribute page to the guide in the docs.  This will create a one stop shop for new users and contributors to get them started and assumes less about how used they are to dealing with GitHub.

It's also makes some more minor improvements to the other pages.

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
@Cadair, can you confirm whether I've done the links between pages correctly.  I am never sure.

**Comment by DanRyanIrish** [comment]
@BaptistePellorceAstro, would you be interested in giving this PR a quick review?  It's just documentation changes so it just needs a quick read through.  Then add any comments you have, e.g. if there are any parts that are unclear, etc.

There are a lot of files changed, but the only ones that you need to look through are ```contributing.rst``` and ```getting_help.rst```.

If you want to see the files rendered in a more readable format, click the "View" button in the top right corner of the file's window.

This shouldn't take you too much of your time.  If it does you are probably putting too much effort into it ;)

**Comment by BaptistePellorceAstro** [comment]
Hi, I found it 100% clear about `contributing.rst` and `getting_help.rst`. These files are short and very understandable !

**Comment by DanRyanIrish** [comment]
I'm glad to hear it @BaptistePellorceAstro!  Thanks for looking over it.  Would you like to officially approved the PR?  To do so, go to the "Files changed" tab, then click on the green "Review changes" button, and a drop down window appears.  One of the selectable options is "Approved".  Click that and then click "Submit review".

**Pull request merged**
