### PR TITLE
Remove ArithmeticMixin until we WCS it

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
:+1: Pending tests passing

**Comment by DanRyanIrish** [comment]
Actually I think this does need a changelog and a breaking one at that.  Although it doesn't affect our codebase it's possible someone was using the arithmetic operations, even though they aren't coordinate aware.  SO for them, NDCube will now break when before it would do something.

**Review by DanRyanIrish — APPROVED** [review]

**Comment by dhomeier** [comment]
`specutils` has been using the arithmetic throughout, so is massively broken by this change.

**Comment by DanRyanIrish** [comment]
Thanks for pointing this out.  We clearly merged this too hastily.  Let's find the best solution so `specutils` is not too impacted.

**Comment by dhomeier** [comment]
I think your proposed fix of subclassing directly to `NDArithmeticMixin` at least restores the previous functionality.
I don't think specutils `Spectrum1D.add` at this point intends to provide any functionality to actually co-add spectra co-add spectra on different grids; the only test is just using two spectral axes with different units, and not checking the results.
In fact `spectrum1 + spectrum2` just ignores differences in `spectral_axis` as long as the shapes match.

**Comment by DanRyanIrish** [comment]
Thanks for the clarifications @dhomeier.  In that case we can leave this PR merged as is.

**Pull request merged**
